### PR TITLE
Add GeoStats.jl

### PR DESCRIPTION
**Pull request by juliohm**
Project name:

Project website/repository:

License:

Checklist for new projects:

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Created a new category only if necessary.
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by juliohm** [comment]
Could you please take a look at this?

Thank you,
-Julio

**Comment by leouieda** [comment]
Hi Julio, thanks for the contribution :+1:  The failing test is unrelated. I'll fix that and then merge this in.

**Comment by leouieda** [comment]
@juliohm please update your branch with the latest commits from *master* and fill out our pull request template (copied in the PR body above).

**Comment by juliohm** [comment]
Thank you @leouieda , opened a new PR. Closing this one.

**Pull request closed without merging**
