### PR TITLE
Add OpendTect-Plugins

### PR DESCRIPTION
**Pull request by waynegm**
Project name: OpendTect-Plugins

Project website/repository: https://github.com/waynegm/OpendTect-Plugins

License: GPL

Checklist for new projects:

- [ ] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

- [ ] Easily Accessible
- [ ] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Anyone know why the Travis check's failed? I can't understand the "details" section. Otherwise looks good to me

**Comment by JesperDramsch** [comment]
The Agile* cheat sheets aren't found anymore...

**Comment by JustinGOSSES** [comment]
The cheatsheet links work, so I'm guessing this was a short-term issue.

**Comment by JustinGOSSES** [comment]
@waynegm can you push this pull request. I think it should pass checks as the links it flagged as non-valid are working today.  If I don't hear from you, I'll fork your repo and do this via another pull request. Cheers

**Comment by JustinGOSSES** [comment]
@waynegm can you re-fork, make your edits, and submit a new pull request once this one here: https://github.com/softwareunderground/awesome-open-geoscience has been approved. We're running into some travis CI issues with links breaking between the time of the version you forked and the version now.  Just mentione this pull request #104 and we'll approve. Thanks.

**Comment by JustinGOSSES** [comment]
This has been accomplished via other pull request so closing this one.

**Pull request closed without merging**
