### PR TITLE
Add PyLops

### PR DESCRIPTION
**Pull request by prisae**
Project name: PyLops

Project website/repository: https://pylops.readthedocs.io

License: LGPL 3.0

Checklist for new projects:

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Added the link to the bottom of the relevant category.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.
- [x] Created a new category only if necessary.
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace (set your text editor to do this automatically).

### CODE REVIEW

**Comment by prisae** [comment]
I don't get it. First Travis complained about
```
1. [L037] 301 https://pylops.readthedocs.io  → http://pylops.readthedocs.io/en/latest/ 
```
so I added the `/en/latest`. Then it complained
```
1. [L037] 301 https://pylops.readthedocs.io/en/latest/  → http://pylops.readthedocs.io/en/latest/ 
```
so I changed https to http, and then it complained
```
1. [L037] 301 http://pylops.readthedocs.io/en/latest/  → https://pylops.readthedocs.io/en/latest/ 
```
Anyone has an idea?

**Comment by mrava87** [comment]
Could it be because the last build failed (going beyond memory limit in one of the new examples) although readthedocs is smart and persist the documentation of last successful build so travis should understand that too? ;)

**Comment by JesperDramsch** [comment]
@mrava87 wenn are not using readthedocs.

_Sent from my OnePlus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prisae** [comment]
You were right, I was missing the trailing slash. Quite picky, that thing...

**Comment by JesperDramsch** [comment]
Yeah. It triggers on all redirects and technically from no slash to slash is a redirect. That one is a bit annoying but it's quite useful in other situations, like the change from Statoil to equinor.

**Comment by mrava87** [comment]
Sounds good, agree with category :)

**Comment by prisae** [comment]
I think the Travis-checks got stuck...

**Comment by mrava87** [comment]
You could switch to the GitHub repo instead as for other libraries if that makes life easier, the link to readthedocs is in there anyways :)

**Comment by JesperDramsch** [comment]
Restarted it manually

**Pull request merged**
