### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abuseki**
Add EarthChem

__Project name:__ EarthChem

__Project website/repository:__ https://www.earthchem.org/

__License:__ Five CC licenses are allowed for contributons: `CC BY-SA 4.0` recommended and default for submissions of new data sets.\
Other CC licenses contributors can choose from: `CC BY 4.0`, `CC BY-NC-SA 4.0`, `CC BY-NC-SA 3.0 US`, `CC0`.

__Submission type:__ New Data Repository

## Checklist for all pull requests:

- [X] Project is [`certified awesome`](awesome.md)

- [X] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [X] Searched the existing entries to make sure this is not a duplicate.
- [X] Contains only a single addition (make separate PRs if adding more than one).
- [X] Added the link to the bottom of the relevant category.
- [X] Created a new category only if necessary.

- [X] Add icon from the `media/icon/` folder if applicable (e.g., `Python` ).
- [X] Checked spelling and grammar.
- [X] Removed trailing whitespace and periods.
- [X] Confirm the dash – is not a minus -.
- [X] Used [title-casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (AP style) for project name.

### Checklist for new software projects:

- [ ] Link the code repository rather than the website/documentation
- [ ] Installation instructions present
- [ ] Documentation looks great
- [ ] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

### Checklist for new Data Repositories, Tutorials and Cheat Sheets, and Miscellaneous:

- [X] Easily accessible
- [X] Comprehensive and widely appealing

### CODE REVIEW

**Comment by mmcint** [comment]
@abuseki I see that you're adding several links here. are these all associated with `earthchem`?

**Comment by JustinGOSSES** [comment]
Typically one contribution at a time is best. This is because one contribution might not qualify or take longer.

However, probably not worth breaking up this PR once already submitted unless we see a problem with any of the contributions.

I can take the geochron ones as I used the excel addon back in the day and would like to check them out.

**Review by JustinGOSSES — APPROVED** [review]
These all seem good. Cool to see some of the geochron tasks I did in grad school now in a nicer python toolkit.

**Comment by JustinGOSSES** [comment]
Fixed two URL bugs with issues unrelated to this pull request but that had to be fixed to get CI to pass.

**Comment by JustinGOSSES** [comment]
Thanks @abuseki and @mmcint

**Pull request merged**
