### PR TITLE
link to awesome open climate science

### PR DESCRIPTION
**Pull request by rabernat**
As discussed in #60, this would a cross reference to the new [awesome-open-climate-science](https://github.com/pangeo-data/awesome-open-climate-science) list.

### CODE REVIEW

**Comment by lheagy** [comment]
:wave: @JesperDramsch: would you like to take a quick look before we merge?

**Comment by leouieda** [comment]
Maybe we should have another category at the top for similar awesome lists. We already list Awesome Geospatial below.

**Comment by JesperDramsch** [comment]
Related awesomeness would be cool imho. We could then also mention it in the contributors guide.

**Comment by rabernat** [comment]
Please feel free to edit my branch directly and modify however you see fit. My one hope is that the links to the other list[s] can be near the top, rather than buried towards the bottom.

**Comment by JesperDramsch** [comment]
It's ok if you add the new category related awesome to the top of the content of our list. Please remember to put the awesome geospatial list there as well and adhere to the fromatting guidelines.

**Comment by lheagy** [comment]
Just to clarify, where do you think we should add the "related awesome"? I agree that it makes sense to have is near the top of the list as it is a bit more high-level content. I have a screenshot below with two possible locations. Please see what you think and I can help make some updates here too. 

image

**Comment by JesperDramsch** [comment]
2 would be ok imho. @leouieda?

**Comment by leouieda** [comment]
2 sounds good to me :+1:

**Comment by lheagy** [comment]
Thanks for the update @rabernat! @JesperDramsch: would you mind taking a look when you have a chance?

**Comment by JesperDramsch** [comment]
I removed the definition of our list in the description, as it was factually wrong. Everything's merged now.

**Comment by rabernat** [comment]
The “factually wrong” statement in question was:

> This list focuses on solid-earth geoscience.

That was my interpretation of the outcome of the discussion in #60. If you don’t agree with that characterization, it would still be useful to have some clear statement regarding the scope of this list. What belongs on this list and what doesn’t?

“Geoscience” in general can easily be construed to mean all aspects of Earth System Science.

**Comment by JesperDramsch** [comment]
We have reservoir engineering on the list, some geospatial stuff, and I'd rather have a conversation as we did in #60 than push away people because they might be slightly tangential.

I'd also prefer to leave the definition part to the maintainers of the list if that would be fine with you. You seem to have some strong opinions about the list and I'd rather talk about them than get a PR. As we did with almost all the changes you might see in the Issues. (Platform category, dataset icons, open publications, is one example.) This thing took a ton of work, as you may see in the commit history, please respect that we do in fact like a bit of ownership over the definition of the list ourselves. (Well I should speak for myself here tbh. I would like to maintain the definition of the list.) 

You have a big section at the top of the list directly linking to the climate and the spatial list, which gives a lot of context. Once more lists come up, they get a prominent place there to further define the scope. If you don't think that is enough, let's take it back to the issues please and discuss among all of Swung to make a better description together. But as you may have taken from the discussion in #60: It's not that easy to define the scope.

**Comment by rabernat** [comment]
No disrespect was meant at any point. Sincere apologies for having overstepped.

**Comment by JesperDramsch** [comment]
No harm done. I just figured open communication would be the most appropriate here. I'm sorry if I came off rude.

**Comment by leouieda** [comment]
@JesperDramsch @rabernat just wanted to say that I'm happy to see such quick de-escalation :) Language barriers are tough to overcome with text.

As @JesperDramsch pointed out, we've had multiple discussions here and on the slack channel about definitions for our scope and what we mean by "geoscience". It's tough to be inclusive because there are so many different disciplines that can easily be excluded with a word choice. For example, "geoscience" excludes planetary sciences and petroleum engineers and "solid earth" traditionally excludes applied geophysics.

An alternative would be define the things that are clearly out of scope (in this case, climate/ocean). We could add a note at the "related awesome" saying that contributions in these categories should be made to those lists instead. What do you think?

**Pull request merged**
