### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KoalaGeo**
Addition of BGS Sigma, BGS Groundhog and GemPy

### CODE REVIEW

**Comment by JesperDramsch** [comment]
Hey @KoalaGeo,

Thanks for contributing. I see you've added GemPy. This is already included in the "Modelling and simulation" section. Would the other package fit there as well?

**Comment by KoalaGeo** [comment]
Hi, 

Sorry, your right, they can go under the Modelling and Simulation section, I've ammended the file to reflect this. 

Regarding the source, unfortunately at the moment the British Geological Survey is unable to release the code, however I still thought it was useful to list the tools here, which are freely available and could be of use to the community.   


At the moment the BGS is unable to release the code, however, I thought it was useful for the community to know these tools are available for free.

**Comment by JesperDramsch** [comment]
That is really unfortunate. At the moment we only accept open contributions to the list, for reproducibility and educational purposes.

**Comment by leouieda** [comment]
Sorry @KoalaGeo but I have to second Jesper's decision here.

**Comment by KoalaGeo** [comment]
Understood, no problem. I'll continue to work on seeing if these projects could be made Open at some point in the future.

**Comment by JesperDramsch** [comment]
That would be fantastic!

**Comment by JesperDramsch** [comment]
Just a motivator. These can be submitted to the Journal of OpenSource Software and getting contributors is usually quite nice in improving the documentation and often even code.

**Pull request closed without merging**
