### PR TITLE
Add empymod

### PR DESCRIPTION
**Pull request by prisae**
Project name: empymod

Project website/repository: https://empymod.github.io

License: Apache v2

Checklist for new projects:

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Added the link to the bottom of the relevant category.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.
- [x] Created a new category only if necessary.
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace (set your text editor to do this automatically).

### CODE REVIEW

**Comment by JesperDramsch** [comment]
Thanks for the contribution! Glad to see them coming.

Would you mind rephrasing the comment on empymod to exclude the explicit mention of Python and open source? The language is covered by the icons and everything on the list is open source.

**Comment by prisae** [comment]
Can do that. However, regarding the icons: I cannot see them:
screenshot

Firefox 65, Ubuntu 18.04.

**Comment by JesperDramsch** [comment]
@prisae oh wow. Would you mind opening an issue with this? It's probably a problem with SVGs.

_Sent from my OnePlus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prisae** [comment]
In Chrome the icons work. But not in Firefox. Will open an issue.

**Comment by JesperDramsch** [comment]
Looks good. Thanks!

**Pull request merged**
