### PR TITLE
Add PetroPy

### PR DESCRIPTION
**Pull request by toddheitmann**
Project name: PetroPy

Project website/repository: [GitHub](https://github.com/toddheitmann/PetroPy)

License: MIT License

PetroPy can be installed with pip to perform petrophysical calculations, output las files, and log images. It's fully open sourced.

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

- [x] Easily Accessible
- [x] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
In the description can you add a note along the lines of "includes basic well log visualization via matplotlib." That's important to note for potential users. Once that change occurs, ping me and I'll approve/merge.

**Comment by toddheitmann** [comment]
Updated description. Thanks!

**Comment by JustinGOSSES** [comment]
Ugh, Travis CI is stopping me from merging in your pull request as 3 links are being 301 redirected and apparently Travis CI doesn't like that. 

I submitted this pull request that fixes the links: https://github.com/softwareunderground/awesome-open-geoscience/pull/107 but I can't approve my own pull request even as admin, so have to wait for one of the other approvers to approve. 

After the pull request mentions is merged, you should be able to re-trip Travis CI to build, it will pass, and then myself or someone else can merge. Sorry for delay.

**Comment by toddheitmann** [comment]
Reran in #108. Thanks.

**Pull request closed without merging**
