### PR TITLE
Changed link to new UK NDR

### PR DESCRIPTION
**Pull request by kwinkunks**
Project name: UK NDR - updating link

Project website/repository:

License:

Checklist for new projects:

- [ ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ ] Searched the existing entries to make sure this is not a duplicate.
- [ ] Contains only a single addition (make separate PRs if adding more than one).
- [ ] Added the link to the bottom of the relevant category.
- [ ] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [ ] Created a new category only if necessary.
- [ ] Checked spelling and grammar.
- [ ] Removed trailing whitespace and periods.
- [ ] Confirm the dash – is not a minus -.
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by leouieda** [comment]
@JesperDramsch do we care about this type of redirect? It's taking from the canonical URL to a login URL. Don't know if that should be an issue. Is there any way to whitelist this or should we change the URL to https://ndr.ogauthority.co.uk/dp/controller/ ?

**Comment by JesperDramsch** [comment]
Personally, I'd prefer not growing the exception list, because web apps don't have their redirects under control. It is the instant redirect they chose for their TLD therefore I'd treat it as canonical. We could alternatively link to the about page.

**Comment by JesperDramsch** [comment]
https://www.ogauthority.co.uk/data-centre/national-data-repository-ndr/

**Comment by leouieda** [comment]
Shall we try the redirect first? If it breaks, Travis will let us know.

**Comment by JesperDramsch** [comment]
Probably best.

**Comment by leouieda** [comment]
:+1: thanks @kwinkunks and @JesperDramsch

**Pull request merged**
