### PR TITLE
Update readme - pyinterpolate package

### PR DESCRIPTION
**Pull request by SimonMolinsky**
__Project name:__ Pyinterpolate

__Project website/repository:__ https://github.com/DataverseLabs/pyinterpolate

__License:__ BSD-3-Clause

__Submission type:__ New Software Project

## Checklist for all pull requests:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Add icon from the `media/icon/` folder if applicable (e.g., `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (AP style) for project name.

### Checklist for new software projects:

- [x] Link the code repository rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [x] Tests and Travis CI running

### Checklist for new Data Repositories, Tutorials and Cheat Sheets, and Miscellaneous:

- [x] Easily accessible
- [x] Comprehensive and widely appealing

### CODE REVIEW

**Review by JustinGOSSES — CHANGES_REQUESTED** [review]
If I try to install with 3.10, the install breaks. If I try to install with conda, doesn't work as 3.7 isn't one of the available versions in Anaconda anymore.  

Can you update installation to work with more recent Python version that is available in the default channel of anaconda as you use that in the installation instructions (which are otherwise awesome!).

**Comment by SimonMolinsky** [comment]
Hi @JustinGOSSES ,

Thank you for your time & comment! I was aware that the package works only with Python 3.7, but I haven't known that conda stopped support for this version. The good news is that for the last few months I have been upgrading the package to work with Python 3.7 - 3.10, so soon it will be available. Based on your comment, rather sooner than I initially planned.

I'll let you know when the problem is gone. Thank you again!

**Comment by SimonMolinsky** [comment]
Hi @JustinGOSSES ,

As I said, the new version of the package is out. Now it works with P3.7-P3.10. If you plan to test it, I recommend using README (setup desc) and the tutorials section where you can quickly try the API: https://github.com/DataverseLabs/pyinterpolate/tree/main/tutorials

**Review by JustinGOSSES — APPROVED** [review]
Got the examples to work now. Thank you.

**Pull request merged**
