### PR TITLE
Added Auralib to Seismic and Seismology

### PR DESCRIPTION
**Pull request by mycarta**
Project name: Auralib

Project website/repository: https://github.com/whamlyn/auralib

License: Apache 2.0

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [ ] Installation instructions present
- [ ] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

- [ ] Easily Accessible
- [x] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [ ] Checked spelling and grammar.
- [ ] Removed trailing whitespace and periods.
- [ ] Confirm the dash – is not a minus -.
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Single line description is pretty broad. Suspect it doesn't cover quite everything you might imagine from that statement so what is in and out of scope? 

It would really help if there was documentation on overall architecture, use, and what is or isn't inside scope. Add that and I'm fine approving, otherwise a bit confusing?

**Comment by mycarta** [comment]
I will check with the author

**Comment by JustinGOSSES** [comment]
anyone want to take this on?

**Comment by mycarta** [comment]
There's now a notebook with everal examples [in here](https://github.com/whamlyn/auralib/blob/master/examples/Calgary%20Python%20Geosciences%20Meetup%20-%2020171108%20-%20Wes%20Hamlyn.ipynb)

**Review by JustinGOSSES — APPROVED** [review]

**Pull request merged**
