### PR TITLE
Add the GeoStat-Framework

### PR DESCRIPTION
**Pull request by MuellerSeb**
This PR is addressing Issue https://github.com/softwareunderground/awesome-open-geoscience/issues/94.

Project name: GeoStat-Framework

Project website/repository: https://github.com/GeoStat-Framework

License: LGPL and MIT

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [x] Tests and Travis CI running

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by MuellerSeb** [comment]
Ah, i got duplicated links, since I added a new Framework category (like in awesome-open-climate-science) and I also added some of the links to the special categories.

How to deal with this? Should I keep the list of contained packages in the framework short and without special links and add the detailed packages to the special categories?

Thank you.
Sebastian

**Comment by banesullivan** [comment]
I would only add one link for the “GeoStat-Framework” under the geostatistics section. I don’t think a new section is warranted here.

Only the project itself should to be listed. All of the sub tools shouldn’t be here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JesperDramsch** [comment]
I figure it's in a similar situation like Leo's fatiando. 

I'd vote to file it under geostatistics (or maybe simulation).

**Comment by MuellerSeb** [comment]
> I figure it's in a similar situation like Leo's fatiando.

OK, I used that as a guide and removed the Frameworks category.
Better now or really just one addition? I think, for example, ogs5py should be under simulation, since its not specifically connected to geo-statistics.

**Comment by JesperDramsch** [comment]
One per pull request, please. The one you submitted.

**Comment by MuellerSeb** [comment]
@JesperDramsch ok, I only add the GeoStat-Framework. Sorry for the inconvenience!

Cheers, Sebastian

**Pull request merged**
