### PR TITLE
Digitize Heatap

### PR DESCRIPTION
**Pull request by RyanFu008**
__Project name:__
- Digitize Heatmap

__Project website/repository:__ 
- [https://github.com/RyanFu008/digitize-heatmap](https://github.com/RyanFu008/digitize-heatmap)

__License:__ 
- MIT License

__Submission type:__
- New Software Project

## Checklist for all pull requests:

- [ ] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Add icon from the `media/icon/` folder if applicable (e.g., `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [ x Used [title-casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (AP style) for project name.

### Checklist for new software projects:

- [x] Link the code repository rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running
  - This seems difficult to do - I would greatly appreciate feedback on this point

### CODE REVIEW

**Comment by ahinoamp** [comment]
Hi can someone on the maintanance team explain what else is necessary for this PR to go through?

**Comment by JustinGOSSES** [comment]
Sorry for the slow reply. Will try to get to this later today.

**Review by JustinGOSSES — APPROVED** [review]
It isn't only useful for heatmaps, but probably fine to just say heatmaps at least in this limited space?

**Comment by JustinGOSSES** [comment]
Hi @RyanFu008 and @ahinoamp . I took a look at this and tried it out. Cool! Left a few enhancement suggestions in the repo's issues, mostly just related to helping people new to the tool get going quickly. Nothing big, just little stuff that's hard to see once you've stared at something so much. 

https://github.com/RyanFu008/digitize-heatmap/issues

**Pull request merged**
