### PR TITLE
SVG -> PNG

### PR DESCRIPTION
**Pull request by JesperDramsch**
Switch to PNG

### CODE REVIEW

**Comment by JesperDramsch** [comment]
No worries, all checks are failing because one website is undergoing maintenance.

**Comment by prisae** [comment]
https://ags.aer.ca/publications/SPE_006.html  => They do maintenance..., so it fails

**Comment by prisae** [comment]
Ha! Sorry, you mentioned the maintenance already, didn't see it...

**Comment by JesperDramsch** [comment]
> Ha! Sorry, you mentioned the maintenance already, didn't see it...

No worries, wanted to save you time :)

**Comment by prisae** [comment]
Solved #58

**Comment by leouieda** [comment]
Looking at the SVGs, they were actually just an embeded base64 encoded PNG anyway.

**Pull request merged**
