### PR TITLE
Initial Formulation of our Awesome Manifesto

### PR DESCRIPTION
**Pull request by JesperDramsch**
Added all of the following and edited the text to be more "awesome focused"

Open Licensing, Software, Software, Unacceptable, Software Documentation, Readme, Installation Instructions, Examples and Tutorials, API Documentation, Software Tests, Datasets, Dataset Documentation, Download Instructions, Publications and Cheat Sheets, Project Community Guidelines

### CODE REVIEW

**Comment by JesperDramsch** [comment]
Awesome

**Comment by JustinGOSSES** [comment]
Cloned your pull request and made some minor languages changes in tone, but then messed up the git push back up. Changes seemed to have pushed to correct branch but not your pull request on that branch, effectively skipping your pull request. Sorry about that. ....I'll resist complaining about git. 

The resulting changes are in your branch @JesperDramsch here: https://github.com/softwareunderground/awesome-open-geoscience/blob/JesperDramsch-awesome-manifesto/awesome.md

**Comment by JesperDramsch** [comment]
@JustinGOSSES looks like they're in here, right above your comment. :)

**Comment by JesperDramsch** [comment]
@kwinkunks @leouieda would you like to crank up the awesome as well?

**Pull request merged**
