### PR TITLE
Update README, added Groundhog

### PR DESCRIPTION
**Pull request by blue-granite**
__Project name:__ BGS Groundhog

__Project website/repository:__ https://www.bgs.ac.uk/technologies/software/groundhog/

__License:__ MIT

__Submission type:__
"New Software Project" 

## Checklist for all pull requests:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [ ] Created a new category only if necessary.

- [x] Add icon from the `media/icon/` folder if applicable (e.g., `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (AP style) for project name.

### Checklist for new software projects:

- [ ] Link the code repository rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

### Checklist for new Data Repositories, Tutorials and Cheat Sheets, and Miscellaneous:

- [ ] Easily accessible
- [ ] Comprehensive and widely appealing

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
@blue-granite I see the website for this currently says it is depreciated and no longer supported due to a lack of funding. Typically, that would imply it shouldn't be listed on this list as the project is abandoned. However, we are open to arguments otherwise if you have reasons why it should still be listed on the Awesome list?

**Comment by RichardScottOZ** [comment]
That is how I understood it...did not check if was still available when I found that out

**Comment by blue-granite** [comment]
Groundhog is actively used within the https://www.bgs.ac.uk/

I'm one of the developers at the BGS that has been tasked with producing new builds of Groundhog, I'm not one of the original development team. There is no further development planned for new features, **however** we periodically produce new maintenance builds with updated dependencies.

If there is anything else I can clarify - just ask.

**Comment by JustinGOSSES** [comment]
I tried to find links on the page linked to screenshots and documentation, but there were none. 

Like many people, I don't like downloading large installation files that take several minutes to download before I understand what an application does and how I might use it. Hence, this would have stopped me immediately normally, but for the purposes of this pull request I downloaded it anyways. It turns out it is a Windows only file, so I couldn't install it on my MacOS. Did not see any information on the download page that says it works for Windows only. 

To be awesome, there really needs to be more information about what it does, who would use it to do what, and instructions on how to install and use it. Also, the fact that there is no way for the community to contribute back or make improvements is not awesome. https://github.com/softwareunderground/awesome-open-geoscience/blob/main/awesome.md

Needs: 
- [ ] More information on operating system requirements
- [ ] Installation instructions
- [ ] Documentation: how to use

The lack of active development and lack of potential for community contributions is problematic, but could be passable as there are plans to support security updates.

**Comment by blue-granite** [comment]
I will discuss the matter with my colleagues and get back to you.
Thanks.

**Comment by JustinGOSSES** [comment]
Closing this for lack of activity but can reopen as needed if anyone wants

**Pull request closed without merging**
