### PR TITLE
Change vista descriptions

### PR DESCRIPTION
**Pull request by banesullivan**
Project name: `vista`

These changes update the descriptions of `vista` based software in accordance with its recent name change.

### CODE REVIEW

**Comment by willsa14** [comment]
Hey @banesullivan, are you aware of the [VISTA](https://www.software.slb.com/products/vista) seismic processing suite? I think this is a bit close for comfort here. (Full disclosure: I'm at Schlumberger, though mostly I coincidence that I noticed this.)

**Comment by banesullivan** [comment]
Thanks for pointing this out, @willsa14 - I was unaware of that software’s existence

While yes, our `vista` can be used to visualize geoscientific data (and notably seismic), the scope of our software is very different from Schlumberger’s software. 

We are not making any claims that our software can replace Schlumberger’s software, nor are we using the name `vista` in any capacity such that anyone could interpret its as being a direct product of Schlumberger. Our `vista` (technically we are branding it as `PyVista`) is a general purpose mesh analysis and visualization Python package and not a seismic focused library.

Furthermore, we changed our name from `vtki` to `vista` to distinguish our software from Kitware’s VTK library. 

I greatly appreciate you bringing this to my attention and would be happy to follow up further with you and/or anyone at Schlumberger via info@pyvista.org

**Comment by prisae** [comment]
I guess there was Windows Vista too, so Schlumberger can't claim the `Vista`-brand for themselves...

**Comment by willsa14** [comment]
Hey @banesullivan @prisae tough sell for me because I read about how complicated these things get sometimes. However, it's your project of course and I just wanted to let you know! I've been hearing about `vtki` / `vista` for a bit now through the slack and seems like you are doing some good stuff!

**Comment by leouieda** [comment]
Hi @willsa14 thanks for point it out. It's so hard to choose good unique names. Do you anticipate any trouble from Schlumberger because of the name? They probably have a trademark on it.

**Comment by prisae** [comment]
Had a chat yesterday with @willsa14, and he is probably right. If `vista` stays smallish, it most likely won't be a problem. If it becomes big or very well known, then it might become a problem. And you don't want to fight their lawyers, I guess. Difficult thing to which I don't know the answer either.

**Comment by banesullivan** [comment]
Thanks, @prisae! 

> If vista stays smallish, it most likely won't be a problem.

I see a lot of potential in `vtki`/`vista`/`pyvista` so I want to choose a name that won't be problematic if it were to become a widely used software - my goal is for it to one day be the 3D visualization and mesh framework of choice in Python. This might be an overzealous goal, but it's important for me to choose a name that will not result in a legal death of the project before it has the chance to get there.

> If it becomes big or very well known, then it might become a problem. And you don't want to fight their lawyers, I guess.

Yeah... even if they don't have exclusive rights to the name `vista`, it won't be about that, it'll simply come down to the fact that an open-source project won't be able to afford a legal battle. 

# Choosing a new name

@willsa14 and @prisae: I'm thinking the name `PyVista` is sufficiently different, thoughts?

FYI, it looks like [these creators](https://monkeybyte.com) of [Vista/Vista Pro](https://en.wikipedia.org/wiki/VistaPro) have the rights to the software name

**Comment by JesperDramsch** [comment]
I think pyVista should be sufficiently different, considering the ubiquity of vista itself.

**Comment by prisae** [comment]
I also think that `PyVista` should be fine :+1:

So now we have at least VISTA from Schlumberger, Windows Vista, and Vista the landscape modeller, and `PyVista` is sufficiently different IMHO.

**Comment by banesullivan** [comment]
Awesome, thanks you all!

**Comment by willsa14** [comment]
@banesullivan sorry to go radio-silent on this, since I really don't know about copyright law I was trying to do a little research before I answered. I basically failed, but I did notice that:
- "vista" appears 3200 times as a mark in the U.S. Patent Office site, [190 times](http://tmsearch.uspto.gov/bin/showfield?f=toc&state=4804%3A8hpvkw.1.1&p_search=searchstr&BackReference=&p_L=100&p_plural=yes&p_s_PARA1=vista&p_tagrepl%7E%3A=PARA1%24MP&expr=PARA1+and+PARA2&p_s_PARA2=software&p_tagrepl%7E%3A=PARA2%24ALL&a_default=search&f=toc&state=4804%3A8hpvkw.1.1&a_search=Submit+Query) with software in the description
(You are in 
- "pyvista" appears never
> It's so hard to choose good unique names.
- I tried brainstorming more unique names, my neighbor suggested `drishi` which is Sanskrit for "vision" -- and it turns out there is a [business visualization tool](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4804:8hpvkw.10.1) with this mark. *+1* for @leouieda's comment.

**Pull request merged**
